// Generated by gencpp from file lslidar_cx_driver/data_portRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_DATA_PORTREQUEST_H
#define LSLIDAR_CX_DRIVER_MESSAGE_DATA_PORTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_cx_driver
{
template <class ContainerAllocator>
struct data_portRequest_
{
  typedef data_portRequest_<ContainerAllocator> Type;

  data_portRequest_()
    : data_port(0)  {
    }
  data_portRequest_(const ContainerAllocator& _alloc)
    : data_port(0)  {
  (void)_alloc;
    }



   typedef int32_t _data_port_type;
  _data_port_type data_port;





  typedef boost::shared_ptr< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> const> ConstPtr;

}; // struct data_portRequest_

typedef ::lslidar_cx_driver::data_portRequest_<std::allocator<void> > data_portRequest;

typedef boost::shared_ptr< ::lslidar_cx_driver::data_portRequest > data_portRequestPtr;
typedef boost::shared_ptr< ::lslidar_cx_driver::data_portRequest const> data_portRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data_port == rhs.data_port;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_cx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e3599314372b45e051224eae0fc6c5d";
  }

  static const char* value(const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e3599314372b45eULL;
  static const uint64_t static_value2 = 0x051224eae0fc6c5dULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_cx_driver/data_portRequest";
  }

  static const char* value(const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 data_port\n"
;
  }

  static const char* value(const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_portRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_cx_driver::data_portRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_cx_driver::data_portRequest_<ContainerAllocator>& v)
  {
    s << indent << "data_port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data_port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_DATA_PORTREQUEST_H
