// Generated by gencpp from file lslidar_cx_driver/data_port.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_DATA_PORT_H
#define LSLIDAR_CX_DRIVER_MESSAGE_DATA_PORT_H

#include <ros/service_traits.h>


#include <lslidar_cx_driver/data_portRequest.h>
#include <lslidar_cx_driver/data_portResponse.h>


namespace lslidar_cx_driver
{

struct data_port
{

typedef data_portRequest Request;
typedef data_portResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct data_port
} // namespace lslidar_cx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_cx_driver::data_port > {
  static const char* value()
  {
    return "f7cc218a25293cd22056167a1e74a99d";
  }

  static const char* value(const ::lslidar_cx_driver::data_port&) { return value(); }
};

template<>
struct DataType< ::lslidar_cx_driver::data_port > {
  static const char* value()
  {
    return "lslidar_cx_driver/data_port";
  }

  static const char* value(const ::lslidar_cx_driver::data_port&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_cx_driver::data_portRequest> should match
// service_traits::MD5Sum< ::lslidar_cx_driver::data_port >
template<>
struct MD5Sum< ::lslidar_cx_driver::data_portRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_cx_driver::data_port >::value();
  }
  static const char* value(const ::lslidar_cx_driver::data_portRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_cx_driver::data_portRequest> should match
// service_traits::DataType< ::lslidar_cx_driver::data_port >
template<>
struct DataType< ::lslidar_cx_driver::data_portRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_cx_driver::data_port >::value();
  }
  static const char* value(const ::lslidar_cx_driver::data_portRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_cx_driver::data_portResponse> should match
// service_traits::MD5Sum< ::lslidar_cx_driver::data_port >
template<>
struct MD5Sum< ::lslidar_cx_driver::data_portResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_cx_driver::data_port >::value();
  }
  static const char* value(const ::lslidar_cx_driver::data_portResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_cx_driver::data_portResponse> should match
// service_traits::DataType< ::lslidar_cx_driver::data_port >
template<>
struct DataType< ::lslidar_cx_driver::data_portResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_cx_driver::data_port >::value();
  }
  static const char* value(const ::lslidar_cx_driver::data_portResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_DATA_PORT_H
