// Generated by gencpp from file lslidar_cx_driver/destination_ipRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_DESTINATION_IPREQUEST_H
#define LSLIDAR_CX_DRIVER_MESSAGE_DESTINATION_IPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_cx_driver
{
template <class ContainerAllocator>
struct destination_ipRequest_
{
  typedef destination_ipRequest_<ContainerAllocator> Type;

  destination_ipRequest_()
    : destination_ip()  {
    }
  destination_ipRequest_(const ContainerAllocator& _alloc)
    : destination_ip(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _destination_ip_type;
  _destination_ip_type destination_ip;





  typedef boost::shared_ptr< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> const> ConstPtr;

}; // struct destination_ipRequest_

typedef ::lslidar_cx_driver::destination_ipRequest_<std::allocator<void> > destination_ipRequest;

typedef boost::shared_ptr< ::lslidar_cx_driver::destination_ipRequest > destination_ipRequestPtr;
typedef boost::shared_ptr< ::lslidar_cx_driver::destination_ipRequest const> destination_ipRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator2> & rhs)
{
  return lhs.destination_ip == rhs.destination_ip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_cx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ded2a85d419004140c5dca203d3d95b4";
  }

  static const char* value(const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xded2a85d41900414ULL;
  static const uint64_t static_value2 = 0x0c5dca203d3d95b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_cx_driver/destination_ipRequest";
  }

  static const char* value(const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string destination_ip\n"
;
  }

  static const char* value(const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination_ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct destination_ipRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_cx_driver::destination_ipRequest_<ContainerAllocator>& v)
  {
    s << indent << "destination_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination_ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_DESTINATION_IPREQUEST_H
