// Generated by gencpp from file lslidar_cx_driver/dev_portRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_DEV_PORTREQUEST_H
#define LSLIDAR_CX_DRIVER_MESSAGE_DEV_PORTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_cx_driver
{
template <class ContainerAllocator>
struct dev_portRequest_
{
  typedef dev_portRequest_<ContainerAllocator> Type;

  dev_portRequest_()
    : dev_port(0)  {
    }
  dev_portRequest_(const ContainerAllocator& _alloc)
    : dev_port(0)  {
  (void)_alloc;
    }



   typedef int32_t _dev_port_type;
  _dev_port_type dev_port;





  typedef boost::shared_ptr< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> const> ConstPtr;

}; // struct dev_portRequest_

typedef ::lslidar_cx_driver::dev_portRequest_<std::allocator<void> > dev_portRequest;

typedef boost::shared_ptr< ::lslidar_cx_driver::dev_portRequest > dev_portRequestPtr;
typedef boost::shared_ptr< ::lslidar_cx_driver::dev_portRequest const> dev_portRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dev_port == rhs.dev_port;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_cx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b92caaac30c40fb9b589f8794e70f44";
  }

  static const char* value(const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b92caaac30c40fbULL;
  static const uint64_t static_value2 = 0x9b589f8794e70f44ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_cx_driver/dev_portRequest";
  }

  static const char* value(const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 dev_port\n"
;
  }

  static const char* value(const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dev_port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dev_portRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_cx_driver::dev_portRequest_<ContainerAllocator>& v)
  {
    s << indent << "dev_port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dev_port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_DEV_PORTREQUEST_H
