// Generated by gencpp from file lslidar_cx_driver/lslidar_controlRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_LSLIDAR_CONTROLREQUEST_H
#define LSLIDAR_CX_DRIVER_MESSAGE_LSLIDAR_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_cx_driver
{
template <class ContainerAllocator>
struct lslidar_controlRequest_
{
  typedef lslidar_controlRequest_<ContainerAllocator> Type;

  lslidar_controlRequest_()
    : laser_control(0)  {
    }
  lslidar_controlRequest_(const ContainerAllocator& _alloc)
    : laser_control(0)  {
  (void)_alloc;
    }



   typedef int32_t _laser_control_type;
  _laser_control_type laser_control;





  typedef boost::shared_ptr< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct lslidar_controlRequest_

typedef ::lslidar_cx_driver::lslidar_controlRequest_<std::allocator<void> > lslidar_controlRequest;

typedef boost::shared_ptr< ::lslidar_cx_driver::lslidar_controlRequest > lslidar_controlRequestPtr;
typedef boost::shared_ptr< ::lslidar_cx_driver::lslidar_controlRequest const> lslidar_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.laser_control == rhs.laser_control;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_cx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d04c062893c0d3566fc8cfe1bb5bf133";
  }

  static const char* value(const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd04c062893c0d356ULL;
  static const uint64_t static_value2 = 0x6fc8cfe1bb5bf133ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_cx_driver/lslidar_controlRequest";
  }

  static const char* value(const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 laser_control\n"
;
  }

  static const char* value(const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laser_control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lslidar_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_cx_driver::lslidar_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "laser_control: ";
    Printer<int32_t>::stream(s, indent + "  ", v.laser_control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_LSLIDAR_CONTROLREQUEST_H
