// Generated by gencpp from file lslidar_cx_driver/motor_control.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_MOTOR_CONTROL_H
#define LSLIDAR_CX_DRIVER_MESSAGE_MOTOR_CONTROL_H

#include <ros/service_traits.h>


#include <lslidar_cx_driver/motor_controlRequest.h>
#include <lslidar_cx_driver/motor_controlResponse.h>


namespace lslidar_cx_driver
{

struct motor_control
{

typedef motor_controlRequest Request;
typedef motor_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_control
} // namespace lslidar_cx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_cx_driver::motor_control > {
  static const char* value()
  {
    return "307d227221bb36a842541608aa239174";
  }

  static const char* value(const ::lslidar_cx_driver::motor_control&) { return value(); }
};

template<>
struct DataType< ::lslidar_cx_driver::motor_control > {
  static const char* value()
  {
    return "lslidar_cx_driver/motor_control";
  }

  static const char* value(const ::lslidar_cx_driver::motor_control&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_cx_driver::motor_controlRequest> should match
// service_traits::MD5Sum< ::lslidar_cx_driver::motor_control >
template<>
struct MD5Sum< ::lslidar_cx_driver::motor_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_cx_driver::motor_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::motor_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_cx_driver::motor_controlRequest> should match
// service_traits::DataType< ::lslidar_cx_driver::motor_control >
template<>
struct DataType< ::lslidar_cx_driver::motor_controlRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_cx_driver::motor_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::motor_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_cx_driver::motor_controlResponse> should match
// service_traits::MD5Sum< ::lslidar_cx_driver::motor_control >
template<>
struct MD5Sum< ::lslidar_cx_driver::motor_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_cx_driver::motor_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::motor_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_cx_driver::motor_controlResponse> should match
// service_traits::DataType< ::lslidar_cx_driver::motor_control >
template<>
struct DataType< ::lslidar_cx_driver::motor_controlResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_cx_driver::motor_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::motor_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_MOTOR_CONTROL_H
