// Generated by gencpp from file lslidar_cx_driver/remove_control.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_REMOVE_CONTROL_H
#define LSLIDAR_CX_DRIVER_MESSAGE_REMOVE_CONTROL_H

#include <ros/service_traits.h>


#include <lslidar_cx_driver/remove_controlRequest.h>
#include <lslidar_cx_driver/remove_controlResponse.h>


namespace lslidar_cx_driver
{

struct remove_control
{

typedef remove_controlRequest Request;
typedef remove_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct remove_control
} // namespace lslidar_cx_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_cx_driver::remove_control > {
  static const char* value()
  {
    return "bdd6a9c7cf1a09e7831f35133efa0e8b";
  }

  static const char* value(const ::lslidar_cx_driver::remove_control&) { return value(); }
};

template<>
struct DataType< ::lslidar_cx_driver::remove_control > {
  static const char* value()
  {
    return "lslidar_cx_driver/remove_control";
  }

  static const char* value(const ::lslidar_cx_driver::remove_control&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_cx_driver::remove_controlRequest> should match
// service_traits::MD5Sum< ::lslidar_cx_driver::remove_control >
template<>
struct MD5Sum< ::lslidar_cx_driver::remove_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_cx_driver::remove_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::remove_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_cx_driver::remove_controlRequest> should match
// service_traits::DataType< ::lslidar_cx_driver::remove_control >
template<>
struct DataType< ::lslidar_cx_driver::remove_controlRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_cx_driver::remove_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::remove_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_cx_driver::remove_controlResponse> should match
// service_traits::MD5Sum< ::lslidar_cx_driver::remove_control >
template<>
struct MD5Sum< ::lslidar_cx_driver::remove_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_cx_driver::remove_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::remove_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_cx_driver::remove_controlResponse> should match
// service_traits::DataType< ::lslidar_cx_driver::remove_control >
template<>
struct DataType< ::lslidar_cx_driver::remove_controlResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_cx_driver::remove_control >::value();
  }
  static const char* value(const ::lslidar_cx_driver::remove_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_REMOVE_CONTROL_H
