// Generated by gencpp from file lslidar_cx_driver/remove_controlRequest.msg
// DO NOT EDIT!


#ifndef LSLIDAR_CX_DRIVER_MESSAGE_REMOVE_CONTROLREQUEST_H
#define LSLIDAR_CX_DRIVER_MESSAGE_REMOVE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_cx_driver
{
template <class ContainerAllocator>
struct remove_controlRequest_
{
  typedef remove_controlRequest_<ContainerAllocator> Type;

  remove_controlRequest_()
    : remove_control(0)  {
    }
  remove_controlRequest_(const ContainerAllocator& _alloc)
    : remove_control(0)  {
  (void)_alloc;
    }



   typedef int32_t _remove_control_type;
  _remove_control_type remove_control;





  typedef boost::shared_ptr< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct remove_controlRequest_

typedef ::lslidar_cx_driver::remove_controlRequest_<std::allocator<void> > remove_controlRequest;

typedef boost::shared_ptr< ::lslidar_cx_driver::remove_controlRequest > remove_controlRequestPtr;
typedef boost::shared_ptr< ::lslidar_cx_driver::remove_controlRequest const> remove_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.remove_control == rhs.remove_control;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator1> & lhs, const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_cx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35697986514032f8003bd9ed91d5e759";
  }

  static const char* value(const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35697986514032f8ULL;
  static const uint64_t static_value2 = 0x003bd9ed91d5e759ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_cx_driver/remove_controlRequest";
  }

  static const char* value(const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 remove_control\n"
;
  }

  static const char* value(const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remove_control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remove_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_cx_driver::remove_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "remove_control: ";
    Printer<int32_t>::stream(s, indent + "  ", v.remove_control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_CX_DRIVER_MESSAGE_REMOVE_CONTROLREQUEST_H
